/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRedfishV1SFSSInstanceZoneDBs200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRedfishV1SFSSInstanceZoneDBs200Response{}

// GetRedfishV1SFSSInstanceZoneDBs200Response 
type GetRedfishV1SFSSInstanceZoneDBs200Response struct {
	// Zone database
	ZoneDBs []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner `json:"ZoneDBs"`
	// Number of zone databases
	ZoneDBsodataCount float32 `json:"ZoneDBs@odata.count"`
	OdataId string `json:"@odata.id"`
	OdataContext string `json:"@odata.context"`
	OdataType string `json:"@odata.type"`
}

type _GetRedfishV1SFSSInstanceZoneDBs200Response GetRedfishV1SFSSInstanceZoneDBs200Response

// NewGetRedfishV1SFSSInstanceZoneDBs200Response instantiates a new GetRedfishV1SFSSInstanceZoneDBs200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRedfishV1SFSSInstanceZoneDBs200Response(zoneDBs []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner, zoneDBsodataCount float32, odataId string, odataContext string, odataType string) *GetRedfishV1SFSSInstanceZoneDBs200Response {
	this := GetRedfishV1SFSSInstanceZoneDBs200Response{}
	this.ZoneDBs = zoneDBs
	this.ZoneDBsodataCount = zoneDBsodataCount
	this.OdataId = odataId
	this.OdataContext = odataContext
	this.OdataType = odataType
	return &this
}

// NewGetRedfishV1SFSSInstanceZoneDBs200ResponseWithDefaults instantiates a new GetRedfishV1SFSSInstanceZoneDBs200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRedfishV1SFSSInstanceZoneDBs200ResponseWithDefaults() *GetRedfishV1SFSSInstanceZoneDBs200Response {
	this := GetRedfishV1SFSSInstanceZoneDBs200Response{}
	return &this
}

// GetZoneDBs returns the ZoneDBs field value
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) GetZoneDBs() []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner {
	if o == nil {
		var ret []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner
		return ret
	}

	return o.ZoneDBs
}

// GetZoneDBsOk returns a tuple with the ZoneDBs field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) GetZoneDBsOk() ([]GetRedfishV1SFSSInstanceHosts200ResponseHostsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.ZoneDBs, true
}

// SetZoneDBs sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) SetZoneDBs(v []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner) {
	o.ZoneDBs = v
}

// GetZoneDBsodataCount returns the ZoneDBsodataCount field value
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) GetZoneDBsodataCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ZoneDBsodataCount
}

// GetZoneDBsodataCountOk returns a tuple with the ZoneDBsodataCount field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) GetZoneDBsodataCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZoneDBsodataCount, true
}

// SetZoneDBsodataCount sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) SetZoneDBsodataCount(v float32) {
	o.ZoneDBsodataCount = v
}

// GetOdataId returns the OdataId field value
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) GetOdataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) GetOdataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataId, true
}

// SetOdataId sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) SetOdataId(v string) {
	o.OdataId = v
}

// GetOdataContext returns the OdataContext field value
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) GetOdataContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataContext
}

// GetOdataContextOk returns a tuple with the OdataContext field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) GetOdataContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataContext, true
}

// SetOdataContext sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) SetOdataContext(v string) {
	o.OdataContext = v
}

// GetOdataType returns the OdataType field value
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) GetOdataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataType
}

// GetOdataTypeOk returns a tuple with the OdataType field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) GetOdataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataType, true
}

// SetOdataType sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) SetOdataType(v string) {
	o.OdataType = v
}

func (o GetRedfishV1SFSSInstanceZoneDBs200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRedfishV1SFSSInstanceZoneDBs200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ZoneDBs"] = o.ZoneDBs
	toSerialize["ZoneDBs@odata.count"] = o.ZoneDBsodataCount
	toSerialize["@odata.id"] = o.OdataId
	toSerialize["@odata.context"] = o.OdataContext
	toSerialize["@odata.type"] = o.OdataType
	return toSerialize, nil
}

func (o *GetRedfishV1SFSSInstanceZoneDBs200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ZoneDBs",
		"ZoneDBs@odata.count",
		"@odata.id",
		"@odata.context",
		"@odata.type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRedfishV1SFSSInstanceZoneDBs200Response := _GetRedfishV1SFSSInstanceZoneDBs200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRedfishV1SFSSInstanceZoneDBs200Response)

	if err != nil {
		return err
	}

	*o = GetRedfishV1SFSSInstanceZoneDBs200Response(varGetRedfishV1SFSSInstanceZoneDBs200Response)

	return err
}

type NullableGetRedfishV1SFSSInstanceZoneDBs200Response struct {
	value *GetRedfishV1SFSSInstanceZoneDBs200Response
	isSet bool
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBs200Response) Get() *GetRedfishV1SFSSInstanceZoneDBs200Response {
	return v.value
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBs200Response) Set(val *GetRedfishV1SFSSInstanceZoneDBs200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBs200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBs200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRedfishV1SFSSInstanceZoneDBs200Response(val *GetRedfishV1SFSSInstanceZoneDBs200Response) *NullableGetRedfishV1SFSSInstanceZoneDBs200Response {
	return &NullableGetRedfishV1SFSSInstanceZoneDBs200Response{value: val, isSet: true}
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBs200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBs200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


