/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner{}

// GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner struct for GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner
type GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner struct {
	// Unique zone alias identifier
	ZoneAliasId string `json:"ZoneAliasId"`
	// Friendly name for the zone alias
	ZoneAliasName string `json:"ZoneAliasName"`
	// Number of zone members that are part of the zone alias
	NumberZoneMembers string `json:"NumberZoneMembers"`
	OdataId string `json:"@odata.id"`
	OdataType string `json:"@odata.type"`
	OdataContext string `json:"@odata.context"`
}

type _GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner

// NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner instantiates a new GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner(zoneAliasId string, zoneAliasName string, numberZoneMembers string, odataId string, odataType string, odataContext string) *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner {
	this := GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner{}
	this.ZoneAliasId = zoneAliasId
	this.ZoneAliasName = zoneAliasName
	this.NumberZoneMembers = numberZoneMembers
	this.OdataId = odataId
	this.OdataType = odataType
	this.OdataContext = odataContext
	return &this
}

// NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInnerWithDefaults instantiates a new GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInnerWithDefaults() *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner {
	this := GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner{}
	return &this
}

// GetZoneAliasId returns the ZoneAliasId field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetZoneAliasId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZoneAliasId
}

// GetZoneAliasIdOk returns a tuple with the ZoneAliasId field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetZoneAliasIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZoneAliasId, true
}

// SetZoneAliasId sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) SetZoneAliasId(v string) {
	o.ZoneAliasId = v
}

// GetZoneAliasName returns the ZoneAliasName field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetZoneAliasName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZoneAliasName
}

// GetZoneAliasNameOk returns a tuple with the ZoneAliasName field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetZoneAliasNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZoneAliasName, true
}

// SetZoneAliasName sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) SetZoneAliasName(v string) {
	o.ZoneAliasName = v
}

// GetNumberZoneMembers returns the NumberZoneMembers field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetNumberZoneMembers() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NumberZoneMembers
}

// GetNumberZoneMembersOk returns a tuple with the NumberZoneMembers field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetNumberZoneMembersOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumberZoneMembers, true
}

// SetNumberZoneMembers sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) SetNumberZoneMembers(v string) {
	o.NumberZoneMembers = v
}

// GetOdataId returns the OdataId field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetOdataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetOdataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataId, true
}

// SetOdataId sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) SetOdataId(v string) {
	o.OdataId = v
}

// GetOdataType returns the OdataType field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetOdataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataType
}

// GetOdataTypeOk returns a tuple with the OdataType field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetOdataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataType, true
}

// SetOdataType sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) SetOdataType(v string) {
	o.OdataType = v
}

// GetOdataContext returns the OdataContext field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetOdataContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataContext
}

// GetOdataContextOk returns a tuple with the OdataContext field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) GetOdataContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataContext, true
}

// SetOdataContext sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) SetOdataContext(v string) {
	o.OdataContext = v
}

func (o GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ZoneAliasId"] = o.ZoneAliasId
	toSerialize["ZoneAliasName"] = o.ZoneAliasName
	toSerialize["NumberZoneMembers"] = o.NumberZoneMembers
	toSerialize["@odata.id"] = o.OdataId
	toSerialize["@odata.type"] = o.OdataType
	toSerialize["@odata.context"] = o.OdataContext
	return toSerialize, nil
}

func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ZoneAliasId",
		"ZoneAliasName",
		"NumberZoneMembers",
		"@odata.id",
		"@odata.type",
		"@odata.context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner := _GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner)

	if err != nil {
		return err
	}

	*o = GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner(varGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner)

	return err
}

type NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner struct {
	value *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner
	isSet bool
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) Get() *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner {
	return v.value
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) Set(val *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner(val *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner {
	return &NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner{value: val, isSet: true}
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasSourceConfigExpandZoneAlias200ResponseZoneAliasInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


