/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
)

// checks if the GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner{}

// GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner struct for GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner
type GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner struct {
	OdataId *string `json:"@odata.id,omitempty"`
}

// NewGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner instantiates a new GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner() *GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner {
	this := GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner{}
	return &this
}

// NewGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInnerWithDefaults instantiates a new GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInnerWithDefaults() *GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner {
	this := GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner{}
	return &this
}

// GetOdataId returns the OdataId field value if set, zero value otherwise.
func (o *GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) GetOdataId() string {
	if o == nil || IsNil(o.OdataId) {
		var ret string
		return ret
	}
	return *o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) GetOdataIdOk() (*string, bool) {
	if o == nil || IsNil(o.OdataId) {
		return nil, false
	}
	return o.OdataId, true
}

// HasOdataId returns a boolean if a field has been set.
func (o *GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) HasOdataId() bool {
	if o != nil && !IsNil(o.OdataId) {
		return true
	}

	return false
}

// SetOdataId gets a reference to the given string and assigns it to the OdataId field.
func (o *GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) SetOdataId(v string) {
	o.OdataId = &v
}

func (o GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OdataId) {
		toSerialize["@odata.id"] = o.OdataId
	}
	return toSerialize, nil
}

type NullableGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner struct {
	value *GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner
	isSet bool
}

func (v NullableGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) Get() *GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner {
	return v.value
}

func (v *NullableGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) Set(val *GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner(val *GetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) *NullableGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner {
	return &NullableGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner{value: val, isSet: true}
}

func (v NullableGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRedfishV1SFSSInstanceSubsystems200ResponseSubsystemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


