/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostsGETExpandHostsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostsGETExpandHostsInner{}

// HostsGETExpandHostsInner struct for HostsGETExpandHostsInner
type HostsGETExpandHostsInner struct {
	// Unique Identity of the Entity - Fully Qualified Name (FQN) of the host
	Id string `json:"Id"`
	// NVMe Qualified Name (NQN) of the host
	NQN string `json:"NQN"`
	// IP address of the host
	TransportAddress string `json:"TransportAddress"`
	// IP address family; possible values include IPv4 and IPv6
	TransportAddressFamily string `json:"TransportAddressFamily"`
	// Protocol used for communication with the host; possible value is TCP
	TransportType string `json:"TransportType"`
	// Transport Request Type (TREQ); possible values include Secure channel not specified, Secure channel required, and Secure channel not required
	TREQ string `json:"TREQ"`
	// Possible values are No Security and TLS
	TSAS string `json:"TSAS"`
	// Type of endpoint registration; possible values include Implicit, Explicit, Pull, and Manual
	RegistrationType string `json:"RegistrationType"`
	// Status of the TCP connection between the host and the CDC instance; possible values include Online and Offline
	ConnectionStatus string `json:"ConnectionStatus"`
	// Reason for the host being offline; possible values include NONE, KATO, and Peer Closure
	FailureReason string `json:"FailureReason"`
	OdataId string `json:"@odata.id"`
	OdataType string `json:"@odata.type"`
	OdataContext string `json:"@odata.context"`
}

type _HostsGETExpandHostsInner HostsGETExpandHostsInner

// NewHostsGETExpandHostsInner instantiates a new HostsGETExpandHostsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostsGETExpandHostsInner(id string, nQN string, transportAddress string, transportAddressFamily string, transportType string, tREQ string, tSAS string, registrationType string, connectionStatus string, failureReason string, odataId string, odataType string, odataContext string) *HostsGETExpandHostsInner {
	this := HostsGETExpandHostsInner{}
	this.Id = id
	this.NQN = nQN
	this.TransportAddress = transportAddress
	this.TransportAddressFamily = transportAddressFamily
	this.TransportType = transportType
	this.TREQ = tREQ
	this.TSAS = tSAS
	this.RegistrationType = registrationType
	this.ConnectionStatus = connectionStatus
	this.FailureReason = failureReason
	this.OdataId = odataId
	this.OdataType = odataType
	this.OdataContext = odataContext
	return &this
}

// NewHostsGETExpandHostsInnerWithDefaults instantiates a new HostsGETExpandHostsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostsGETExpandHostsInnerWithDefaults() *HostsGETExpandHostsInner {
	this := HostsGETExpandHostsInner{}
	return &this
}

// GetId returns the Id field value
func (o *HostsGETExpandHostsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *HostsGETExpandHostsInner) SetId(v string) {
	o.Id = v
}

// GetNQN returns the NQN field value
func (o *HostsGETExpandHostsInner) GetNQN() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NQN
}

// GetNQNOk returns a tuple with the NQN field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetNQNOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NQN, true
}

// SetNQN sets field value
func (o *HostsGETExpandHostsInner) SetNQN(v string) {
	o.NQN = v
}

// GetTransportAddress returns the TransportAddress field value
func (o *HostsGETExpandHostsInner) GetTransportAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportAddress
}

// GetTransportAddressOk returns a tuple with the TransportAddress field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetTransportAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportAddress, true
}

// SetTransportAddress sets field value
func (o *HostsGETExpandHostsInner) SetTransportAddress(v string) {
	o.TransportAddress = v
}

// GetTransportAddressFamily returns the TransportAddressFamily field value
func (o *HostsGETExpandHostsInner) GetTransportAddressFamily() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportAddressFamily
}

// GetTransportAddressFamilyOk returns a tuple with the TransportAddressFamily field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetTransportAddressFamilyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportAddressFamily, true
}

// SetTransportAddressFamily sets field value
func (o *HostsGETExpandHostsInner) SetTransportAddressFamily(v string) {
	o.TransportAddressFamily = v
}

// GetTransportType returns the TransportType field value
func (o *HostsGETExpandHostsInner) GetTransportType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportType
}

// GetTransportTypeOk returns a tuple with the TransportType field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetTransportTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportType, true
}

// SetTransportType sets field value
func (o *HostsGETExpandHostsInner) SetTransportType(v string) {
	o.TransportType = v
}

// GetTREQ returns the TREQ field value
func (o *HostsGETExpandHostsInner) GetTREQ() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TREQ
}

// GetTREQOk returns a tuple with the TREQ field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetTREQOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TREQ, true
}

// SetTREQ sets field value
func (o *HostsGETExpandHostsInner) SetTREQ(v string) {
	o.TREQ = v
}

// GetTSAS returns the TSAS field value
func (o *HostsGETExpandHostsInner) GetTSAS() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TSAS
}

// GetTSASOk returns a tuple with the TSAS field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetTSASOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TSAS, true
}

// SetTSAS sets field value
func (o *HostsGETExpandHostsInner) SetTSAS(v string) {
	o.TSAS = v
}

// GetRegistrationType returns the RegistrationType field value
func (o *HostsGETExpandHostsInner) GetRegistrationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistrationType
}

// GetRegistrationTypeOk returns a tuple with the RegistrationType field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetRegistrationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistrationType, true
}

// SetRegistrationType sets field value
func (o *HostsGETExpandHostsInner) SetRegistrationType(v string) {
	o.RegistrationType = v
}

// GetConnectionStatus returns the ConnectionStatus field value
func (o *HostsGETExpandHostsInner) GetConnectionStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionStatus
}

// GetConnectionStatusOk returns a tuple with the ConnectionStatus field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetConnectionStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionStatus, true
}

// SetConnectionStatus sets field value
func (o *HostsGETExpandHostsInner) SetConnectionStatus(v string) {
	o.ConnectionStatus = v
}

// GetFailureReason returns the FailureReason field value
func (o *HostsGETExpandHostsInner) GetFailureReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FailureReason
}

// GetFailureReasonOk returns a tuple with the FailureReason field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetFailureReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailureReason, true
}

// SetFailureReason sets field value
func (o *HostsGETExpandHostsInner) SetFailureReason(v string) {
	o.FailureReason = v
}

// GetOdataId returns the OdataId field value
func (o *HostsGETExpandHostsInner) GetOdataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetOdataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataId, true
}

// SetOdataId sets field value
func (o *HostsGETExpandHostsInner) SetOdataId(v string) {
	o.OdataId = v
}

// GetOdataType returns the OdataType field value
func (o *HostsGETExpandHostsInner) GetOdataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataType
}

// GetOdataTypeOk returns a tuple with the OdataType field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetOdataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataType, true
}

// SetOdataType sets field value
func (o *HostsGETExpandHostsInner) SetOdataType(v string) {
	o.OdataType = v
}

// GetOdataContext returns the OdataContext field value
func (o *HostsGETExpandHostsInner) GetOdataContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataContext
}

// GetOdataContextOk returns a tuple with the OdataContext field value
// and a boolean to check if the value has been set.
func (o *HostsGETExpandHostsInner) GetOdataContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataContext, true
}

// SetOdataContext sets field value
func (o *HostsGETExpandHostsInner) SetOdataContext(v string) {
	o.OdataContext = v
}

func (o HostsGETExpandHostsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostsGETExpandHostsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Id"] = o.Id
	toSerialize["NQN"] = o.NQN
	toSerialize["TransportAddress"] = o.TransportAddress
	toSerialize["TransportAddressFamily"] = o.TransportAddressFamily
	toSerialize["TransportType"] = o.TransportType
	toSerialize["TREQ"] = o.TREQ
	toSerialize["TSAS"] = o.TSAS
	toSerialize["RegistrationType"] = o.RegistrationType
	toSerialize["ConnectionStatus"] = o.ConnectionStatus
	toSerialize["FailureReason"] = o.FailureReason
	toSerialize["@odata.id"] = o.OdataId
	toSerialize["@odata.type"] = o.OdataType
	toSerialize["@odata.context"] = o.OdataContext
	return toSerialize, nil
}

func (o *HostsGETExpandHostsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Id",
		"NQN",
		"TransportAddress",
		"TransportAddressFamily",
		"TransportType",
		"TREQ",
		"TSAS",
		"RegistrationType",
		"ConnectionStatus",
		"FailureReason",
		"@odata.id",
		"@odata.type",
		"@odata.context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostsGETExpandHostsInner := _HostsGETExpandHostsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostsGETExpandHostsInner)

	if err != nil {
		return err
	}

	*o = HostsGETExpandHostsInner(varHostsGETExpandHostsInner)

	return err
}

type NullableHostsGETExpandHostsInner struct {
	value *HostsGETExpandHostsInner
	isSet bool
}

func (v NullableHostsGETExpandHostsInner) Get() *HostsGETExpandHostsInner {
	return v.value
}

func (v *NullableHostsGETExpandHostsInner) Set(val *HostsGETExpandHostsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableHostsGETExpandHostsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableHostsGETExpandHostsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostsGETExpandHostsInner(val *HostsGETExpandHostsInner) *NullableHostsGETExpandHostsInner {
	return &NullableHostsGETExpandHostsInner{value: val, isSet: true}
}

func (v NullableHostsGETExpandHostsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostsGETExpandHostsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


