/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostRedfishV1SFSSInstanceHostsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostRedfishV1SFSSInstanceHostsRequest{}

// PostRedfishV1SFSSInstanceHostsRequest 
type PostRedfishV1SFSSInstanceHostsRequest struct {
	// NVMe Qualified Name (NQN) of the host
	NQN string `json:"NQN"`
	// IP address of the host
	TransportAddress string `json:"TransportAddress"`
	// IP address family; possible values include IPv4 and IPv6
	TransportAddressFamily string `json:"TransportAddressFamily"`
	// Protocol used for communication with the host; possible value is TCP 
	TransportType string `json:"TransportType"`
}

type _PostRedfishV1SFSSInstanceHostsRequest PostRedfishV1SFSSInstanceHostsRequest

// NewPostRedfishV1SFSSInstanceHostsRequest instantiates a new PostRedfishV1SFSSInstanceHostsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostRedfishV1SFSSInstanceHostsRequest(nQN string, transportAddress string, transportAddressFamily string, transportType string) *PostRedfishV1SFSSInstanceHostsRequest {
	this := PostRedfishV1SFSSInstanceHostsRequest{}
	this.NQN = nQN
	this.TransportAddress = transportAddress
	this.TransportAddressFamily = transportAddressFamily
	this.TransportType = transportType
	return &this
}

// NewPostRedfishV1SFSSInstanceHostsRequestWithDefaults instantiates a new PostRedfishV1SFSSInstanceHostsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostRedfishV1SFSSInstanceHostsRequestWithDefaults() *PostRedfishV1SFSSInstanceHostsRequest {
	this := PostRedfishV1SFSSInstanceHostsRequest{}
	return &this
}

// GetNQN returns the NQN field value
func (o *PostRedfishV1SFSSInstanceHostsRequest) GetNQN() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NQN
}

// GetNQNOk returns a tuple with the NQN field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSInstanceHostsRequest) GetNQNOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NQN, true
}

// SetNQN sets field value
func (o *PostRedfishV1SFSSInstanceHostsRequest) SetNQN(v string) {
	o.NQN = v
}

// GetTransportAddress returns the TransportAddress field value
func (o *PostRedfishV1SFSSInstanceHostsRequest) GetTransportAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportAddress
}

// GetTransportAddressOk returns a tuple with the TransportAddress field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSInstanceHostsRequest) GetTransportAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportAddress, true
}

// SetTransportAddress sets field value
func (o *PostRedfishV1SFSSInstanceHostsRequest) SetTransportAddress(v string) {
	o.TransportAddress = v
}

// GetTransportAddressFamily returns the TransportAddressFamily field value
func (o *PostRedfishV1SFSSInstanceHostsRequest) GetTransportAddressFamily() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportAddressFamily
}

// GetTransportAddressFamilyOk returns a tuple with the TransportAddressFamily field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSInstanceHostsRequest) GetTransportAddressFamilyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportAddressFamily, true
}

// SetTransportAddressFamily sets field value
func (o *PostRedfishV1SFSSInstanceHostsRequest) SetTransportAddressFamily(v string) {
	o.TransportAddressFamily = v
}

// GetTransportType returns the TransportType field value
func (o *PostRedfishV1SFSSInstanceHostsRequest) GetTransportType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportType
}

// GetTransportTypeOk returns a tuple with the TransportType field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSInstanceHostsRequest) GetTransportTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportType, true
}

// SetTransportType sets field value
func (o *PostRedfishV1SFSSInstanceHostsRequest) SetTransportType(v string) {
	o.TransportType = v
}

func (o PostRedfishV1SFSSInstanceHostsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostRedfishV1SFSSInstanceHostsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["NQN"] = o.NQN
	toSerialize["TransportAddress"] = o.TransportAddress
	toSerialize["TransportAddressFamily"] = o.TransportAddressFamily
	toSerialize["TransportType"] = o.TransportType
	return toSerialize, nil
}

func (o *PostRedfishV1SFSSInstanceHostsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"NQN",
		"TransportAddress",
		"TransportAddressFamily",
		"TransportType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostRedfishV1SFSSInstanceHostsRequest := _PostRedfishV1SFSSInstanceHostsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostRedfishV1SFSSInstanceHostsRequest)

	if err != nil {
		return err
	}

	*o = PostRedfishV1SFSSInstanceHostsRequest(varPostRedfishV1SFSSInstanceHostsRequest)

	return err
}

type NullablePostRedfishV1SFSSInstanceHostsRequest struct {
	value *PostRedfishV1SFSSInstanceHostsRequest
	isSet bool
}

func (v NullablePostRedfishV1SFSSInstanceHostsRequest) Get() *PostRedfishV1SFSSInstanceHostsRequest {
	return v.value
}

func (v *NullablePostRedfishV1SFSSInstanceHostsRequest) Set(val *PostRedfishV1SFSSInstanceHostsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostRedfishV1SFSSInstanceHostsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostRedfishV1SFSSInstanceHostsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostRedfishV1SFSSInstanceHostsRequest(val *PostRedfishV1SFSSInstanceHostsRequest) *NullablePostRedfishV1SFSSInstanceHostsRequest {
	return &NullablePostRedfishV1SFSSInstanceHostsRequest{value: val, isSet: true}
}

func (v NullablePostRedfishV1SFSSInstanceHostsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostRedfishV1SFSSInstanceHostsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


