/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response{}

// GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response 
type GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response struct {
	// Type of endpoint; possible values include host and subsystem
	Role string `json:"Role"`
	// Unique zone member identifier
	ZoneMemberId string `json:"ZoneMemberId"`
	// Possible values include NVMe Qualified Name (NQN) and Fully Qualified Name (FQN)
	ZoneMemberType string `json:"ZoneMemberType"`
	OdataId string `json:"@odata.id"`
	OdataType string `json:"@odata.type"`
	OdataContext string `json:"@odata.context"`
}

type _GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response

// NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response instantiates a new GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response(role string, zoneMemberId string, zoneMemberType string, odataId string, odataType string, odataContext string) *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response {
	this := GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response{}
	this.Role = role
	this.ZoneMemberId = zoneMemberId
	this.ZoneMemberType = zoneMemberType
	this.OdataId = odataId
	this.OdataType = odataType
	this.OdataContext = odataContext
	return &this
}

// NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200ResponseWithDefaults instantiates a new GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200ResponseWithDefaults() *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response {
	this := GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response{}
	return &this
}

// GetRole returns the Role field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) SetRole(v string) {
	o.Role = v
}

// GetZoneMemberId returns the ZoneMemberId field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetZoneMemberId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZoneMemberId
}

// GetZoneMemberIdOk returns a tuple with the ZoneMemberId field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetZoneMemberIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZoneMemberId, true
}

// SetZoneMemberId sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) SetZoneMemberId(v string) {
	o.ZoneMemberId = v
}

// GetZoneMemberType returns the ZoneMemberType field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetZoneMemberType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZoneMemberType
}

// GetZoneMemberTypeOk returns a tuple with the ZoneMemberType field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetZoneMemberTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZoneMemberType, true
}

// SetZoneMemberType sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) SetZoneMemberType(v string) {
	o.ZoneMemberType = v
}

// GetOdataId returns the OdataId field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetOdataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetOdataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataId, true
}

// SetOdataId sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) SetOdataId(v string) {
	o.OdataId = v
}

// GetOdataType returns the OdataType field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetOdataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataType
}

// GetOdataTypeOk returns a tuple with the OdataType field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetOdataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataType, true
}

// SetOdataType sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) SetOdataType(v string) {
	o.OdataType = v
}

// GetOdataContext returns the OdataContext field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetOdataContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataContext
}

// GetOdataContextOk returns a tuple with the OdataContext field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) GetOdataContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataContext, true
}

// SetOdataContext sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) SetOdataContext(v string) {
	o.OdataContext = v
}

func (o GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Role"] = o.Role
	toSerialize["ZoneMemberId"] = o.ZoneMemberId
	toSerialize["ZoneMemberType"] = o.ZoneMemberType
	toSerialize["@odata.id"] = o.OdataId
	toSerialize["@odata.type"] = o.OdataType
	toSerialize["@odata.context"] = o.OdataContext
	return toSerialize, nil
}

func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Role",
		"ZoneMemberId",
		"ZoneMemberType",
		"@odata.id",
		"@odata.type",
		"@odata.context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response := _GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response)

	if err != nil {
		return err
	}

	*o = GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response(varGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response)

	return err
}

type NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response struct {
	value *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response
	isSet bool
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) Get() *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response {
	return v.value
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) Set(val *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response(val *GetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response {
	return &NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response{value: val, isSet: true}
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGroupIdZonesZoneIDZoneMembersZoneMemberIDSourceConfig200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


