/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response{}

// PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response 
type PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response struct {
	EId string `json:"EId"`
}

type _PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response

// NewPostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response instantiates a new PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response(eId string) *PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response {
	this := PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response{}
	this.EId = eId
	return &this
}

// NewPostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200ResponseWithDefaults instantiates a new PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200ResponseWithDefaults() *PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response {
	this := PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response{}
	return &this
}

// GetEId returns the EId field value
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) GetEId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EId
}

// GetEIdOk returns a tuple with the EId field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) GetEIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EId, true
}

// SetEId sets field value
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) SetEId(v string) {
	o.EId = v
}

func (o PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["EId"] = o.EId
	return toSerialize, nil
}

func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"EId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response := _PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response)

	if err != nil {
		return err
	}

	*o = PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response(varPostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response)

	return err
}

type NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response struct {
	value *PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response
	isSet bool
}

func (v NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) Get() *PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response {
	return v.value
}

func (v *NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) Set(val *PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response(val *PostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) *NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response {
	return &NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response{value: val, isSet: true}
}

func (v NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneGroups200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


