/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response{}

// GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response 
type GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response struct {
	// A set of roles
	Role []string `json:"Role"`
	// Possible values include NVMe Qualified Name (NQN) or Fully Qualified Name (FQN)
	ZoneMemberType []string `json:"ZoneMemberType"`
}

type _GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response

// NewGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response instantiates a new GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response(role []string, zoneMemberType []string) *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response {
	this := GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response{}
	this.Role = role
	this.ZoneMemberType = zoneMemberType
	return &this
}

// NewGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200ResponseWithDefaults instantiates a new GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200ResponseWithDefaults() *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response {
	this := GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response{}
	return &this
}

// GetRole returns the Role field value
func (o *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) GetRole() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) GetRoleOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role, true
}

// SetRole sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) SetRole(v []string) {
	o.Role = v
}

// GetZoneMemberType returns the ZoneMemberType field value
func (o *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) GetZoneMemberType() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ZoneMemberType
}

// GetZoneMemberTypeOk returns a tuple with the ZoneMemberType field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) GetZoneMemberTypeOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ZoneMemberType, true
}

// SetZoneMemberType sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) SetZoneMemberType(v []string) {
	o.ZoneMemberType = v
}

func (o GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Role"] = o.Role
	toSerialize["ZoneMemberType"] = o.ZoneMemberType
	return toSerialize, nil
}

func (o *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Role",
		"ZoneMemberType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response := _GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response)

	if err != nil {
		return err
	}

	*o = GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response(varGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response)

	return err
}

type NullableGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response struct {
	value *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response
	isSet bool
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) Get() *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response {
	return v.value
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) Set(val *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response(val *GetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) *NullableGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response {
	return &NullableGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response{value: val, isSet: true}
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsZoneAliasZoneAliasMembersEnums200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


