/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest{}

// PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest 
type PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest struct {
	// Unique zone alias member identifier
	ZoneAliasMemberId string `json:"ZoneAliasMemberId"`
	// Possible values include NVMe Qualified Name (NQN) and Fully Qualified Name (FQN)
	ZoneAliasMemberType string `json:"ZoneAliasMemberType"`
	// Type of endpoint; possible values include host and subsystem
	Role string `json:"Role"`
}

type _PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest

// NewPostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest instantiates a new PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest(zoneAliasMemberId string, zoneAliasMemberType string, role string) *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest {
	this := PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest{}
	this.ZoneAliasMemberId = zoneAliasMemberId
	this.ZoneAliasMemberType = zoneAliasMemberType
	this.Role = role
	return &this
}

// NewPostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequestWithDefaults instantiates a new PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequestWithDefaults() *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest {
	this := PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest{}
	return &this
}

// GetZoneAliasMemberId returns the ZoneAliasMemberId field value
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) GetZoneAliasMemberId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZoneAliasMemberId
}

// GetZoneAliasMemberIdOk returns a tuple with the ZoneAliasMemberId field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) GetZoneAliasMemberIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZoneAliasMemberId, true
}

// SetZoneAliasMemberId sets field value
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) SetZoneAliasMemberId(v string) {
	o.ZoneAliasMemberId = v
}

// GetZoneAliasMemberType returns the ZoneAliasMemberType field value
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) GetZoneAliasMemberType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZoneAliasMemberType
}

// GetZoneAliasMemberTypeOk returns a tuple with the ZoneAliasMemberType field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) GetZoneAliasMemberTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZoneAliasMemberType, true
}

// SetZoneAliasMemberType sets field value
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) SetZoneAliasMemberType(v string) {
	o.ZoneAliasMemberType = v
}

// GetRole returns the Role field value
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) SetRole(v string) {
	o.Role = v
}

func (o PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ZoneAliasMemberId"] = o.ZoneAliasMemberId
	toSerialize["ZoneAliasMemberType"] = o.ZoneAliasMemberType
	toSerialize["Role"] = o.Role
	return toSerialize, nil
}

func (o *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ZoneAliasMemberId",
		"ZoneAliasMemberType",
		"Role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest := _PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest)

	if err != nil {
		return err
	}

	*o = PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest(varPostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest)

	return err
}

type NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest struct {
	value *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest
	isSet bool
}

func (v NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) Get() *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest {
	return v.value
}

func (v *NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) Set(val *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest(val *PostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) *NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest {
	return &NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest{value: val, isSet: true}
}

func (v NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


