/*
SmartFabric Storage Software Application REST APIs

REST APIs used for managing SFSS application are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssapp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PostRedfishV1SFSSAppRadiusServers200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostRedfishV1SFSSAppRadiusServers200Response{}

// PostRedfishV1SFSSAppRadiusServers200Response
type PostRedfishV1SFSSAppRadiusServers200Response struct {
	// IP address of the RADIUS server; SFSS supports only IPv4 communication with remote servers
	RadiusServer string `json:"RadiusServer"`
}

type _PostRedfishV1SFSSAppRadiusServers200Response PostRedfishV1SFSSAppRadiusServers200Response

// NewPostRedfishV1SFSSAppRadiusServers200Response instantiates a new PostRedfishV1SFSSAppRadiusServers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostRedfishV1SFSSAppRadiusServers200Response(radiusServer string) *PostRedfishV1SFSSAppRadiusServers200Response {
	this := PostRedfishV1SFSSAppRadiusServers200Response{}
	this.RadiusServer = radiusServer
	return &this
}

// NewPostRedfishV1SFSSAppRadiusServers200ResponseWithDefaults instantiates a new PostRedfishV1SFSSAppRadiusServers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostRedfishV1SFSSAppRadiusServers200ResponseWithDefaults() *PostRedfishV1SFSSAppRadiusServers200Response {
	this := PostRedfishV1SFSSAppRadiusServers200Response{}
	return &this
}

// GetRadiusServer returns the RadiusServer field value
func (o *PostRedfishV1SFSSAppRadiusServers200Response) GetRadiusServer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RadiusServer
}

// GetRadiusServerOk returns a tuple with the RadiusServer field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSAppRadiusServers200Response) GetRadiusServerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RadiusServer, true
}

// SetRadiusServer sets field value
func (o *PostRedfishV1SFSSAppRadiusServers200Response) SetRadiusServer(v string) {
	o.RadiusServer = v
}

func (o PostRedfishV1SFSSAppRadiusServers200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostRedfishV1SFSSAppRadiusServers200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["RadiusServer"] = o.RadiusServer
	return toSerialize, nil
}

func (o *PostRedfishV1SFSSAppRadiusServers200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"RadiusServer",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostRedfishV1SFSSAppRadiusServers200Response := _PostRedfishV1SFSSAppRadiusServers200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostRedfishV1SFSSAppRadiusServers200Response)

	if err != nil {
		return err
	}

	*o = PostRedfishV1SFSSAppRadiusServers200Response(varPostRedfishV1SFSSAppRadiusServers200Response)

	return err
}

type NullablePostRedfishV1SFSSAppRadiusServers200Response struct {
	value *PostRedfishV1SFSSAppRadiusServers200Response
	isSet bool
}

func (v NullablePostRedfishV1SFSSAppRadiusServers200Response) Get() *PostRedfishV1SFSSAppRadiusServers200Response {
	return v.value
}

func (v *NullablePostRedfishV1SFSSAppRadiusServers200Response) Set(val *PostRedfishV1SFSSAppRadiusServers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostRedfishV1SFSSAppRadiusServers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostRedfishV1SFSSAppRadiusServers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostRedfishV1SFSSAppRadiusServers200Response(val *PostRedfishV1SFSSAppRadiusServers200Response) *NullablePostRedfishV1SFSSAppRadiusServers200Response {
	return &NullablePostRedfishV1SFSSAppRadiusServers200Response{value: val, isSet: true}
}

func (v NullablePostRedfishV1SFSSAppRadiusServers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostRedfishV1SFSSAppRadiusServers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
