/*
SmartFabric Storage Software Application REST APIs

REST APIs used for managing SFSS application are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssapp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PostRedfishV1SFSSAppFabricManagerInfoPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostRedfishV1SFSSAppFabricManagerInfoPostRequest{}

// PostRedfishV1SFSSAppFabricManagerInfoPostRequest
type PostRedfishV1SFSSAppFabricManagerInfoPostRequest struct {
	// CDC instance identifier; possible values are 1 through 16
	InstanceIdentifier string `json:"InstanceIdentifier"`
	// Interface(s) assigned to the CDC instance
	Interfaces []string `json:"Interfaces"`
	// Administrative state of the CDC instance
	CDCAdminState string `json:"CDCAdminState"`
	// Administrative state of the discovery service
	DiscoverySvcAdminState string `json:"DiscoverySvcAdminState"`
}

type _PostRedfishV1SFSSAppFabricManagerInfoPostRequest PostRedfishV1SFSSAppFabricManagerInfoPostRequest

// NewPostRedfishV1SFSSAppFabricManagerInfoPostRequest instantiates a new PostRedfishV1SFSSAppFabricManagerInfoPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostRedfishV1SFSSAppFabricManagerInfoPostRequest(instanceIdentifier string, interfaces []string, cDCAdminState string, discoverySvcAdminState string) *PostRedfishV1SFSSAppFabricManagerInfoPostRequest {
	this := PostRedfishV1SFSSAppFabricManagerInfoPostRequest{}
	this.InstanceIdentifier = instanceIdentifier
	this.Interfaces = interfaces
	this.CDCAdminState = cDCAdminState
	this.DiscoverySvcAdminState = discoverySvcAdminState
	return &this
}

// NewPostRedfishV1SFSSAppFabricManagerInfoPostRequestWithDefaults instantiates a new PostRedfishV1SFSSAppFabricManagerInfoPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostRedfishV1SFSSAppFabricManagerInfoPostRequestWithDefaults() *PostRedfishV1SFSSAppFabricManagerInfoPostRequest {
	this := PostRedfishV1SFSSAppFabricManagerInfoPostRequest{}
	return &this
}

// GetInstanceIdentifier returns the InstanceIdentifier field value
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) GetInstanceIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceIdentifier
}

// GetInstanceIdentifierOk returns a tuple with the InstanceIdentifier field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) GetInstanceIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceIdentifier, true
}

// SetInstanceIdentifier sets field value
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) SetInstanceIdentifier(v string) {
	o.InstanceIdentifier = v
}

// GetInterfaces returns the Interfaces field value
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) GetInterfaces() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Interfaces
}

// GetInterfacesOk returns a tuple with the Interfaces field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) GetInterfacesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Interfaces, true
}

// SetInterfaces sets field value
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) SetInterfaces(v []string) {
	o.Interfaces = v
}

// GetCDCAdminState returns the CDCAdminState field value
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) GetCDCAdminState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CDCAdminState
}

// GetCDCAdminStateOk returns a tuple with the CDCAdminState field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) GetCDCAdminStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CDCAdminState, true
}

// SetCDCAdminState sets field value
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) SetCDCAdminState(v string) {
	o.CDCAdminState = v
}

// GetDiscoverySvcAdminState returns the DiscoverySvcAdminState field value
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) GetDiscoverySvcAdminState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiscoverySvcAdminState
}

// GetDiscoverySvcAdminStateOk returns a tuple with the DiscoverySvcAdminState field value
// and a boolean to check if the value has been set.
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) GetDiscoverySvcAdminStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiscoverySvcAdminState, true
}

// SetDiscoverySvcAdminState sets field value
func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) SetDiscoverySvcAdminState(v string) {
	o.DiscoverySvcAdminState = v
}

func (o PostRedfishV1SFSSAppFabricManagerInfoPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostRedfishV1SFSSAppFabricManagerInfoPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["InstanceIdentifier"] = o.InstanceIdentifier
	toSerialize["Interfaces"] = o.Interfaces
	toSerialize["CDCAdminState"] = o.CDCAdminState
	toSerialize["DiscoverySvcAdminState"] = o.DiscoverySvcAdminState
	return toSerialize, nil
}

func (o *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"InstanceIdentifier",
		"Interfaces",
		"CDCAdminState",
		"DiscoverySvcAdminState",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostRedfishV1SFSSAppFabricManagerInfoPostRequest := _PostRedfishV1SFSSAppFabricManagerInfoPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostRedfishV1SFSSAppFabricManagerInfoPostRequest)

	if err != nil {
		return err
	}

	*o = PostRedfishV1SFSSAppFabricManagerInfoPostRequest(varPostRedfishV1SFSSAppFabricManagerInfoPostRequest)

	return err
}

type NullablePostRedfishV1SFSSAppFabricManagerInfoPostRequest struct {
	value *PostRedfishV1SFSSAppFabricManagerInfoPostRequest
	isSet bool
}

func (v NullablePostRedfishV1SFSSAppFabricManagerInfoPostRequest) Get() *PostRedfishV1SFSSAppFabricManagerInfoPostRequest {
	return v.value
}

func (v *NullablePostRedfishV1SFSSAppFabricManagerInfoPostRequest) Set(val *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostRedfishV1SFSSAppFabricManagerInfoPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostRedfishV1SFSSAppFabricManagerInfoPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostRedfishV1SFSSAppFabricManagerInfoPostRequest(val *PostRedfishV1SFSSAppFabricManagerInfoPostRequest) *NullablePostRedfishV1SFSSAppFabricManagerInfoPostRequest {
	return &NullablePostRedfishV1SFSSAppFabricManagerInfoPostRequest{value: val, isSet: true}
}

func (v NullablePostRedfishV1SFSSAppFabricManagerInfoPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostRedfishV1SFSSAppFabricManagerInfoPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
