/*
SmartFabric Storage Software Application REST APIs

REST APIs used for managing SFSS application are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssapp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetRedfishV1SFSSAppRadiusServers200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRedfishV1SFSSAppRadiusServers200Response{}

// GetRedfishV1SFSSAppRadiusServers200Response
type GetRedfishV1SFSSAppRadiusServers200Response struct {
	// A set of RADIUS servers
	RadiusServers []GetRedfishV1SFSSAppLicenses200ResponseLicensesInner `json:"RadiusServers"`
	// Number of RADIUS servers configured up to a maximum of 10
	RadiusServersodataCount float32 `json:"RadiusServers@odata.count"`
	OdataId                 string  `json:"@odata.id"`
	OdataContext            string  `json:"@odata.context"`
	OdataType               string  `json:"@odata.type"`
}

type _GetRedfishV1SFSSAppRadiusServers200Response GetRedfishV1SFSSAppRadiusServers200Response

// NewGetRedfishV1SFSSAppRadiusServers200Response instantiates a new GetRedfishV1SFSSAppRadiusServers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRedfishV1SFSSAppRadiusServers200Response(radiusServers []GetRedfishV1SFSSAppLicenses200ResponseLicensesInner, radiusServersodataCount float32, odataId string, odataContext string, odataType string) *GetRedfishV1SFSSAppRadiusServers200Response {
	this := GetRedfishV1SFSSAppRadiusServers200Response{}
	this.RadiusServers = radiusServers
	this.RadiusServersodataCount = radiusServersodataCount
	this.OdataId = odataId
	this.OdataContext = odataContext
	this.OdataType = odataType
	return &this
}

// NewGetRedfishV1SFSSAppRadiusServers200ResponseWithDefaults instantiates a new GetRedfishV1SFSSAppRadiusServers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRedfishV1SFSSAppRadiusServers200ResponseWithDefaults() *GetRedfishV1SFSSAppRadiusServers200Response {
	this := GetRedfishV1SFSSAppRadiusServers200Response{}
	return &this
}

// GetRadiusServers returns the RadiusServers field value
func (o *GetRedfishV1SFSSAppRadiusServers200Response) GetRadiusServers() []GetRedfishV1SFSSAppLicenses200ResponseLicensesInner {
	if o == nil {
		var ret []GetRedfishV1SFSSAppLicenses200ResponseLicensesInner
		return ret
	}

	return o.RadiusServers
}

// GetRadiusServersOk returns a tuple with the RadiusServers field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppRadiusServers200Response) GetRadiusServersOk() ([]GetRedfishV1SFSSAppLicenses200ResponseLicensesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.RadiusServers, true
}

// SetRadiusServers sets field value
func (o *GetRedfishV1SFSSAppRadiusServers200Response) SetRadiusServers(v []GetRedfishV1SFSSAppLicenses200ResponseLicensesInner) {
	o.RadiusServers = v
}

// GetRadiusServersodataCount returns the RadiusServersodataCount field value
func (o *GetRedfishV1SFSSAppRadiusServers200Response) GetRadiusServersodataCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RadiusServersodataCount
}

// GetRadiusServersodataCountOk returns a tuple with the RadiusServersodataCount field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppRadiusServers200Response) GetRadiusServersodataCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RadiusServersodataCount, true
}

// SetRadiusServersodataCount sets field value
func (o *GetRedfishV1SFSSAppRadiusServers200Response) SetRadiusServersodataCount(v float32) {
	o.RadiusServersodataCount = v
}

// GetOdataId returns the OdataId field value
func (o *GetRedfishV1SFSSAppRadiusServers200Response) GetOdataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppRadiusServers200Response) GetOdataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataId, true
}

// SetOdataId sets field value
func (o *GetRedfishV1SFSSAppRadiusServers200Response) SetOdataId(v string) {
	o.OdataId = v
}

// GetOdataContext returns the OdataContext field value
func (o *GetRedfishV1SFSSAppRadiusServers200Response) GetOdataContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataContext
}

// GetOdataContextOk returns a tuple with the OdataContext field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppRadiusServers200Response) GetOdataContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataContext, true
}

// SetOdataContext sets field value
func (o *GetRedfishV1SFSSAppRadiusServers200Response) SetOdataContext(v string) {
	o.OdataContext = v
}

// GetOdataType returns the OdataType field value
func (o *GetRedfishV1SFSSAppRadiusServers200Response) GetOdataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataType
}

// GetOdataTypeOk returns a tuple with the OdataType field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppRadiusServers200Response) GetOdataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataType, true
}

// SetOdataType sets field value
func (o *GetRedfishV1SFSSAppRadiusServers200Response) SetOdataType(v string) {
	o.OdataType = v
}

func (o GetRedfishV1SFSSAppRadiusServers200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRedfishV1SFSSAppRadiusServers200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["RadiusServers"] = o.RadiusServers
	toSerialize["RadiusServers@odata.count"] = o.RadiusServersodataCount
	toSerialize["@odata.id"] = o.OdataId
	toSerialize["@odata.context"] = o.OdataContext
	toSerialize["@odata.type"] = o.OdataType
	return toSerialize, nil
}

func (o *GetRedfishV1SFSSAppRadiusServers200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"RadiusServers",
		"RadiusServers@odata.count",
		"@odata.id",
		"@odata.context",
		"@odata.type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRedfishV1SFSSAppRadiusServers200Response := _GetRedfishV1SFSSAppRadiusServers200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRedfishV1SFSSAppRadiusServers200Response)

	if err != nil {
		return err
	}

	*o = GetRedfishV1SFSSAppRadiusServers200Response(varGetRedfishV1SFSSAppRadiusServers200Response)

	return err
}

type NullableGetRedfishV1SFSSAppRadiusServers200Response struct {
	value *GetRedfishV1SFSSAppRadiusServers200Response
	isSet bool
}

func (v NullableGetRedfishV1SFSSAppRadiusServers200Response) Get() *GetRedfishV1SFSSAppRadiusServers200Response {
	return v.value
}

func (v *NullableGetRedfishV1SFSSAppRadiusServers200Response) Set(val *GetRedfishV1SFSSAppRadiusServers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRedfishV1SFSSAppRadiusServers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRedfishV1SFSSAppRadiusServers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRedfishV1SFSSAppRadiusServers200Response(val *GetRedfishV1SFSSAppRadiusServers200Response) *NullableGetRedfishV1SFSSAppRadiusServers200Response {
	return &NullableGetRedfishV1SFSSAppRadiusServers200Response{value: val, isSet: true}
}

func (v NullableGetRedfishV1SFSSAppRadiusServers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRedfishV1SFSSAppRadiusServers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
