/*
SmartFabric Storage Software Application REST APIs

REST APIs used for managing SFSS application are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssapp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetIDredfishV1SFSSAppSFSSInterfaceList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIDredfishV1SFSSAppSFSSInterfaceList200Response{}

// GetIDredfishV1SFSSAppSFSSInterfaceList200Response
type GetIDredfishV1SFSSAppSFSSInterfaceList200Response struct {
	// A set of available interfaces
	ListOfInterfaces []string `json:"List of Interfaces"`
}

type _GetIDredfishV1SFSSAppSFSSInterfaceList200Response GetIDredfishV1SFSSAppSFSSInterfaceList200Response

// NewGetIDredfishV1SFSSAppSFSSInterfaceList200Response instantiates a new GetIDredfishV1SFSSAppSFSSInterfaceList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIDredfishV1SFSSAppSFSSInterfaceList200Response(listOfInterfaces []string) *GetIDredfishV1SFSSAppSFSSInterfaceList200Response {
	this := GetIDredfishV1SFSSAppSFSSInterfaceList200Response{}
	this.ListOfInterfaces = listOfInterfaces
	return &this
}

// NewGetIDredfishV1SFSSAppSFSSInterfaceList200ResponseWithDefaults instantiates a new GetIDredfishV1SFSSAppSFSSInterfaceList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIDredfishV1SFSSAppSFSSInterfaceList200ResponseWithDefaults() *GetIDredfishV1SFSSAppSFSSInterfaceList200Response {
	this := GetIDredfishV1SFSSAppSFSSInterfaceList200Response{}
	return &this
}

// GetListOfInterfaces returns the ListOfInterfaces field value
func (o *GetIDredfishV1SFSSAppSFSSInterfaceList200Response) GetListOfInterfaces() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ListOfInterfaces
}

// GetListOfInterfacesOk returns a tuple with the ListOfInterfaces field value
// and a boolean to check if the value has been set.
func (o *GetIDredfishV1SFSSAppSFSSInterfaceList200Response) GetListOfInterfacesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ListOfInterfaces, true
}

// SetListOfInterfaces sets field value
func (o *GetIDredfishV1SFSSAppSFSSInterfaceList200Response) SetListOfInterfaces(v []string) {
	o.ListOfInterfaces = v
}

func (o GetIDredfishV1SFSSAppSFSSInterfaceList200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIDredfishV1SFSSAppSFSSInterfaceList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["List of Interfaces"] = o.ListOfInterfaces
	return toSerialize, nil
}

func (o *GetIDredfishV1SFSSAppSFSSInterfaceList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"List of Interfaces",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetIDredfishV1SFSSAppSFSSInterfaceList200Response := _GetIDredfishV1SFSSAppSFSSInterfaceList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetIDredfishV1SFSSAppSFSSInterfaceList200Response)

	if err != nil {
		return err
	}

	*o = GetIDredfishV1SFSSAppSFSSInterfaceList200Response(varGetIDredfishV1SFSSAppSFSSInterfaceList200Response)

	return err
}

type NullableGetIDredfishV1SFSSAppSFSSInterfaceList200Response struct {
	value *GetIDredfishV1SFSSAppSFSSInterfaceList200Response
	isSet bool
}

func (v NullableGetIDredfishV1SFSSAppSFSSInterfaceList200Response) Get() *GetIDredfishV1SFSSAppSFSSInterfaceList200Response {
	return v.value
}

func (v *NullableGetIDredfishV1SFSSAppSFSSInterfaceList200Response) Set(val *GetIDredfishV1SFSSAppSFSSInterfaceList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIDredfishV1SFSSAppSFSSInterfaceList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIDredfishV1SFSSAppSFSSInterfaceList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIDredfishV1SFSSAppSFSSInterfaceList200Response(val *GetIDredfishV1SFSSAppSFSSInterfaceList200Response) *NullableGetIDredfishV1SFSSAppSFSSInterfaceList200Response {
	return &NullableGetIDredfishV1SFSSAppSFSSInterfaceList200Response{value: val, isSet: true}
}

func (v NullableGetIDredfishV1SFSSAppSFSSInterfaceList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIDredfishV1SFSSAppSFSSInterfaceList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
