/*
SmartFabric Storage Software Application REST APIs

REST APIs used for managing SFSS application are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssapp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LicensesGETExpand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LicensesGETExpand{}

// LicensesGETExpand This model lists detailed information about all the licenses installed in SFSS.
type LicensesGETExpand struct {
	// A set of licenses
	Licenses []LicensesGETExpandLicensesInner `json:"Licenses"`
	// Number of licenses installed on the SFSS VM
	LicensesodataCount float32 `json:"Licenses@odata.count"`
	OdataId            string  `json:"@odata.id"`
	OdataContext       string  `json:"@odata.context"`
	OdataType          string  `json:"@odata.type"`
}

type _LicensesGETExpand LicensesGETExpand

// NewLicensesGETExpand instantiates a new LicensesGETExpand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLicensesGETExpand(licenses []LicensesGETExpandLicensesInner, licensesodataCount float32, odataId string, odataContext string, odataType string) *LicensesGETExpand {
	this := LicensesGETExpand{}
	this.Licenses = licenses
	this.LicensesodataCount = licensesodataCount
	this.OdataId = odataId
	this.OdataContext = odataContext
	this.OdataType = odataType
	return &this
}

// NewLicensesGETExpandWithDefaults instantiates a new LicensesGETExpand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLicensesGETExpandWithDefaults() *LicensesGETExpand {
	this := LicensesGETExpand{}
	return &this
}

// GetLicenses returns the Licenses field value
func (o *LicensesGETExpand) GetLicenses() []LicensesGETExpandLicensesInner {
	if o == nil {
		var ret []LicensesGETExpandLicensesInner
		return ret
	}

	return o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value
// and a boolean to check if the value has been set.
func (o *LicensesGETExpand) GetLicensesOk() ([]LicensesGETExpandLicensesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Licenses, true
}

// SetLicenses sets field value
func (o *LicensesGETExpand) SetLicenses(v []LicensesGETExpandLicensesInner) {
	o.Licenses = v
}

// GetLicensesodataCount returns the LicensesodataCount field value
func (o *LicensesGETExpand) GetLicensesodataCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.LicensesodataCount
}

// GetLicensesodataCountOk returns a tuple with the LicensesodataCount field value
// and a boolean to check if the value has been set.
func (o *LicensesGETExpand) GetLicensesodataCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LicensesodataCount, true
}

// SetLicensesodataCount sets field value
func (o *LicensesGETExpand) SetLicensesodataCount(v float32) {
	o.LicensesodataCount = v
}

// GetOdataId returns the OdataId field value
func (o *LicensesGETExpand) GetOdataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value
// and a boolean to check if the value has been set.
func (o *LicensesGETExpand) GetOdataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataId, true
}

// SetOdataId sets field value
func (o *LicensesGETExpand) SetOdataId(v string) {
	o.OdataId = v
}

// GetOdataContext returns the OdataContext field value
func (o *LicensesGETExpand) GetOdataContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataContext
}

// GetOdataContextOk returns a tuple with the OdataContext field value
// and a boolean to check if the value has been set.
func (o *LicensesGETExpand) GetOdataContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataContext, true
}

// SetOdataContext sets field value
func (o *LicensesGETExpand) SetOdataContext(v string) {
	o.OdataContext = v
}

// GetOdataType returns the OdataType field value
func (o *LicensesGETExpand) GetOdataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataType
}

// GetOdataTypeOk returns a tuple with the OdataType field value
// and a boolean to check if the value has been set.
func (o *LicensesGETExpand) GetOdataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataType, true
}

// SetOdataType sets field value
func (o *LicensesGETExpand) SetOdataType(v string) {
	o.OdataType = v
}

func (o LicensesGETExpand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LicensesGETExpand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Licenses"] = o.Licenses
	toSerialize["Licenses@odata.count"] = o.LicensesodataCount
	toSerialize["@odata.id"] = o.OdataId
	toSerialize["@odata.context"] = o.OdataContext
	toSerialize["@odata.type"] = o.OdataType
	return toSerialize, nil
}

func (o *LicensesGETExpand) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Licenses",
		"Licenses@odata.count",
		"@odata.id",
		"@odata.context",
		"@odata.type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLicensesGETExpand := _LicensesGETExpand{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLicensesGETExpand)

	if err != nil {
		return err
	}

	*o = LicensesGETExpand(varLicensesGETExpand)

	return err
}

type NullableLicensesGETExpand struct {
	value *LicensesGETExpand
	isSet bool
}

func (v NullableLicensesGETExpand) Get() *LicensesGETExpand {
	return v.value
}

func (v *NullableLicensesGETExpand) Set(val *LicensesGETExpand) {
	v.value = val
	v.isSet = true
}

func (v NullableLicensesGETExpand) IsSet() bool {
	return v.isSet
}

func (v *NullableLicensesGETExpand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLicensesGETExpand(val *LicensesGETExpand) *NullableLicensesGETExpand {
	return &NullableLicensesGETExpand{value: val, isSet: true}
}

func (v NullableLicensesGETExpand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLicensesGETExpand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
