/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response{}

// DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response 
type DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response struct {
	// A unique NVMe Qualified Name (NQN) of the specified zone
	EId string `json:"EId"`
}

type _DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response

// NewDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response instantiates a new DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response(eId string) *DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response {
	this := DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response{}
	this.EId = eId
	return &this
}

// NewDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200ResponseWithDefaults instantiates a new DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200ResponseWithDefaults() *DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response {
	this := DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response{}
	return &this
}

// GetEId returns the EId field value
func (o *DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) GetEId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EId
}

// GetEIdOk returns a tuple with the EId field value
// and a boolean to check if the value has been set.
func (o *DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) GetEIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EId, true
}

// SetEId sets field value
func (o *DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) SetEId(v string) {
	o.EId = v
}

func (o DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["EId"] = o.EId
	return toSerialize, nil
}

func (o *DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"EId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response := _DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response)

	if err != nil {
		return err
	}

	*o = DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response(varDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response)

	return err
}

type NullableDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response struct {
	value *DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response
	isSet bool
}

func (v NullableDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) Get() *DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response {
	return v.value
}

func (v *NullableDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) Set(val *DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response(val *DeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) *NullableDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response {
	return &NullableDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response{value: val, isSet: true}
}

func (v NullableDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteRedfishV1SFSSInstanceZoneDBsConfigZoneGroupsZoneGrpIDZones200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


