/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubsystemsGET type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubsystemsGET{}

// SubsystemsGET This model contains information about the subsystems that are registered with the CDC instance.
type SubsystemsGET struct {
	// Subsystem information
	Subsystems []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner `json:"Subsystems"`
	// Number of subsystems registered with the CDC instance
	SubsystemsodataCount float32 `json:"Subsystems@odata.count"`
	OdataId string `json:"@odata.id"`
	OdataContext string `json:"@odata.context"`
	OdataType string `json:"@odata.type"`
}

type _SubsystemsGET SubsystemsGET

// NewSubsystemsGET instantiates a new SubsystemsGET object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubsystemsGET(subsystems []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner, subsystemsodataCount float32, odataId string, odataContext string, odataType string) *SubsystemsGET {
	this := SubsystemsGET{}
	this.Subsystems = subsystems
	this.SubsystemsodataCount = subsystemsodataCount
	this.OdataId = odataId
	this.OdataContext = odataContext
	this.OdataType = odataType
	return &this
}

// NewSubsystemsGETWithDefaults instantiates a new SubsystemsGET object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubsystemsGETWithDefaults() *SubsystemsGET {
	this := SubsystemsGET{}
	return &this
}

// GetSubsystems returns the Subsystems field value
func (o *SubsystemsGET) GetSubsystems() []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner {
	if o == nil {
		var ret []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner
		return ret
	}

	return o.Subsystems
}

// GetSubsystemsOk returns a tuple with the Subsystems field value
// and a boolean to check if the value has been set.
func (o *SubsystemsGET) GetSubsystemsOk() ([]GetRedfishV1SFSSInstanceHosts200ResponseHostsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subsystems, true
}

// SetSubsystems sets field value
func (o *SubsystemsGET) SetSubsystems(v []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner) {
	o.Subsystems = v
}

// GetSubsystemsodataCount returns the SubsystemsodataCount field value
func (o *SubsystemsGET) GetSubsystemsodataCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SubsystemsodataCount
}

// GetSubsystemsodataCountOk returns a tuple with the SubsystemsodataCount field value
// and a boolean to check if the value has been set.
func (o *SubsystemsGET) GetSubsystemsodataCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubsystemsodataCount, true
}

// SetSubsystemsodataCount sets field value
func (o *SubsystemsGET) SetSubsystemsodataCount(v float32) {
	o.SubsystemsodataCount = v
}

// GetOdataId returns the OdataId field value
func (o *SubsystemsGET) GetOdataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value
// and a boolean to check if the value has been set.
func (o *SubsystemsGET) GetOdataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataId, true
}

// SetOdataId sets field value
func (o *SubsystemsGET) SetOdataId(v string) {
	o.OdataId = v
}

// GetOdataContext returns the OdataContext field value
func (o *SubsystemsGET) GetOdataContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataContext
}

// GetOdataContextOk returns a tuple with the OdataContext field value
// and a boolean to check if the value has been set.
func (o *SubsystemsGET) GetOdataContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataContext, true
}

// SetOdataContext sets field value
func (o *SubsystemsGET) SetOdataContext(v string) {
	o.OdataContext = v
}

// GetOdataType returns the OdataType field value
func (o *SubsystemsGET) GetOdataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataType
}

// GetOdataTypeOk returns a tuple with the OdataType field value
// and a boolean to check if the value has been set.
func (o *SubsystemsGET) GetOdataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataType, true
}

// SetOdataType sets field value
func (o *SubsystemsGET) SetOdataType(v string) {
	o.OdataType = v
}

func (o SubsystemsGET) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubsystemsGET) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Subsystems"] = o.Subsystems
	toSerialize["Subsystems@odata.count"] = o.SubsystemsodataCount
	toSerialize["@odata.id"] = o.OdataId
	toSerialize["@odata.context"] = o.OdataContext
	toSerialize["@odata.type"] = o.OdataType
	return toSerialize, nil
}

func (o *SubsystemsGET) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Subsystems",
		"Subsystems@odata.count",
		"@odata.id",
		"@odata.context",
		"@odata.type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubsystemsGET := _SubsystemsGET{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubsystemsGET)

	if err != nil {
		return err
	}

	*o = SubsystemsGET(varSubsystemsGET)

	return err
}

type NullableSubsystemsGET struct {
	value *SubsystemsGET
	isSet bool
}

func (v NullableSubsystemsGET) Get() *SubsystemsGET {
	return v.value
}

func (v *NullableSubsystemsGET) Set(val *SubsystemsGET) {
	v.value = val
	v.isSet = true
}

func (v NullableSubsystemsGET) IsSet() bool {
	return v.isSet
}

func (v *NullableSubsystemsGET) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubsystemsGET(val *SubsystemsGET) *NullableSubsystemsGET {
	return &NullableSubsystemsGET{value: val, isSet: true}
}

func (v NullableSubsystemsGET) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubsystemsGET) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


