/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubsystemPOST type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubsystemPOST{}

// SubsystemPOST This model configures a subsystem.
type SubsystemPOST struct {
	NQN string `json:"NQN"`
	TransportAddress string `json:"TransportAddress"`
	TransportAddressFamily string `json:"TransportAddressFamily"`
	PortId float32 `json:"PortId"`
	TransportType string `json:"TransportType"`
	TransportServiceId string `json:"TransportServiceId"`
}

type _SubsystemPOST SubsystemPOST

// NewSubsystemPOST instantiates a new SubsystemPOST object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubsystemPOST(nQN string, transportAddress string, transportAddressFamily string, portId float32, transportType string, transportServiceId string) *SubsystemPOST {
	this := SubsystemPOST{}
	this.NQN = nQN
	this.TransportAddress = transportAddress
	this.TransportAddressFamily = transportAddressFamily
	this.PortId = portId
	this.TransportType = transportType
	this.TransportServiceId = transportServiceId
	return &this
}

// NewSubsystemPOSTWithDefaults instantiates a new SubsystemPOST object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubsystemPOSTWithDefaults() *SubsystemPOST {
	this := SubsystemPOST{}
	return &this
}

// GetNQN returns the NQN field value
func (o *SubsystemPOST) GetNQN() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NQN
}

// GetNQNOk returns a tuple with the NQN field value
// and a boolean to check if the value has been set.
func (o *SubsystemPOST) GetNQNOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NQN, true
}

// SetNQN sets field value
func (o *SubsystemPOST) SetNQN(v string) {
	o.NQN = v
}

// GetTransportAddress returns the TransportAddress field value
func (o *SubsystemPOST) GetTransportAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportAddress
}

// GetTransportAddressOk returns a tuple with the TransportAddress field value
// and a boolean to check if the value has been set.
func (o *SubsystemPOST) GetTransportAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportAddress, true
}

// SetTransportAddress sets field value
func (o *SubsystemPOST) SetTransportAddress(v string) {
	o.TransportAddress = v
}

// GetTransportAddressFamily returns the TransportAddressFamily field value
func (o *SubsystemPOST) GetTransportAddressFamily() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportAddressFamily
}

// GetTransportAddressFamilyOk returns a tuple with the TransportAddressFamily field value
// and a boolean to check if the value has been set.
func (o *SubsystemPOST) GetTransportAddressFamilyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportAddressFamily, true
}

// SetTransportAddressFamily sets field value
func (o *SubsystemPOST) SetTransportAddressFamily(v string) {
	o.TransportAddressFamily = v
}

// GetPortId returns the PortId field value
func (o *SubsystemPOST) GetPortId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PortId
}

// GetPortIdOk returns a tuple with the PortId field value
// and a boolean to check if the value has been set.
func (o *SubsystemPOST) GetPortIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PortId, true
}

// SetPortId sets field value
func (o *SubsystemPOST) SetPortId(v float32) {
	o.PortId = v
}

// GetTransportType returns the TransportType field value
func (o *SubsystemPOST) GetTransportType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportType
}

// GetTransportTypeOk returns a tuple with the TransportType field value
// and a boolean to check if the value has been set.
func (o *SubsystemPOST) GetTransportTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportType, true
}

// SetTransportType sets field value
func (o *SubsystemPOST) SetTransportType(v string) {
	o.TransportType = v
}

// GetTransportServiceId returns the TransportServiceId field value
func (o *SubsystemPOST) GetTransportServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportServiceId
}

// GetTransportServiceIdOk returns a tuple with the TransportServiceId field value
// and a boolean to check if the value has been set.
func (o *SubsystemPOST) GetTransportServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportServiceId, true
}

// SetTransportServiceId sets field value
func (o *SubsystemPOST) SetTransportServiceId(v string) {
	o.TransportServiceId = v
}

func (o SubsystemPOST) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubsystemPOST) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["NQN"] = o.NQN
	toSerialize["TransportAddress"] = o.TransportAddress
	toSerialize["TransportAddressFamily"] = o.TransportAddressFamily
	toSerialize["PortId"] = o.PortId
	toSerialize["TransportType"] = o.TransportType
	toSerialize["TransportServiceId"] = o.TransportServiceId
	return toSerialize, nil
}

func (o *SubsystemPOST) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"NQN",
		"TransportAddress",
		"TransportAddressFamily",
		"PortId",
		"TransportType",
		"TransportServiceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubsystemPOST := _SubsystemPOST{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubsystemPOST)

	if err != nil {
		return err
	}

	*o = SubsystemPOST(varSubsystemPOST)

	return err
}

type NullableSubsystemPOST struct {
	value *SubsystemPOST
	isSet bool
}

func (v NullableSubsystemPOST) Get() *SubsystemPOST {
	return v.value
}

func (v *NullableSubsystemPOST) Set(val *SubsystemPOST) {
	v.value = val
	v.isSet = true
}

func (v NullableSubsystemPOST) IsSet() bool {
	return v.isSet
}

func (v *NullableSubsystemPOST) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubsystemPOST(val *SubsystemPOST) *NullableSubsystemPOST {
	return &NullableSubsystemPOST{value: val, isSet: true}
}

func (v NullableSubsystemPOST) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubsystemPOST) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


