/*
RestServices

REST APIs used for managing CDC instances are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfssrest

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response{}

// GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response 
type GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response struct {
	// A set of zone alias members
	ZoneAliasMembers []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner `json:"ZoneAliasMembers"`
	// Number of zone alias members
	ZoneAliasMembersodataCount float32 `json:"ZoneAliasMembers@odata.count"`
	OdataId string `json:"@odata.id"`
	OdataContext string `json:"@odata.context"`
	OdataType string `json:"@odata.type"`
}

type _GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response

// NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response instantiates a new GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response(zoneAliasMembers []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner, zoneAliasMembersodataCount float32, odataId string, odataContext string, odataType string) *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response {
	this := GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response{}
	this.ZoneAliasMembers = zoneAliasMembers
	this.ZoneAliasMembersodataCount = zoneAliasMembersodataCount
	this.OdataId = odataId
	this.OdataContext = odataContext
	this.OdataType = odataType
	return &this
}

// NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200ResponseWithDefaults instantiates a new GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200ResponseWithDefaults() *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response {
	this := GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response{}
	return &this
}

// GetZoneAliasMembers returns the ZoneAliasMembers field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) GetZoneAliasMembers() []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner {
	if o == nil {
		var ret []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner
		return ret
	}

	return o.ZoneAliasMembers
}

// GetZoneAliasMembersOk returns a tuple with the ZoneAliasMembers field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) GetZoneAliasMembersOk() ([]GetRedfishV1SFSSInstanceHosts200ResponseHostsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.ZoneAliasMembers, true
}

// SetZoneAliasMembers sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) SetZoneAliasMembers(v []GetRedfishV1SFSSInstanceHosts200ResponseHostsInner) {
	o.ZoneAliasMembers = v
}

// GetZoneAliasMembersodataCount returns the ZoneAliasMembersodataCount field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) GetZoneAliasMembersodataCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ZoneAliasMembersodataCount
}

// GetZoneAliasMembersodataCountOk returns a tuple with the ZoneAliasMembersodataCount field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) GetZoneAliasMembersodataCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZoneAliasMembersodataCount, true
}

// SetZoneAliasMembersodataCount sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) SetZoneAliasMembersodataCount(v float32) {
	o.ZoneAliasMembersodataCount = v
}

// GetOdataId returns the OdataId field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) GetOdataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) GetOdataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataId, true
}

// SetOdataId sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) SetOdataId(v string) {
	o.OdataId = v
}

// GetOdataContext returns the OdataContext field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) GetOdataContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataContext
}

// GetOdataContextOk returns a tuple with the OdataContext field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) GetOdataContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataContext, true
}

// SetOdataContext sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) SetOdataContext(v string) {
	o.OdataContext = v
}

// GetOdataType returns the OdataType field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) GetOdataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataType
}

// GetOdataTypeOk returns a tuple with the OdataType field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) GetOdataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataType, true
}

// SetOdataType sets field value
func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) SetOdataType(v string) {
	o.OdataType = v
}

func (o GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ZoneAliasMembers"] = o.ZoneAliasMembers
	toSerialize["ZoneAliasMembers@odata.count"] = o.ZoneAliasMembersodataCount
	toSerialize["@odata.id"] = o.OdataId
	toSerialize["@odata.context"] = o.OdataContext
	toSerialize["@odata.type"] = o.OdataType
	return toSerialize, nil
}

func (o *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ZoneAliasMembers",
		"ZoneAliasMembers@odata.count",
		"@odata.id",
		"@odata.context",
		"@odata.type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response := _GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response)

	if err != nil {
		return err
	}

	*o = GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response(varGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response)

	return err
}

type NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response struct {
	value *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response
	isSet bool
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) Get() *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response {
	return v.value
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) Set(val *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response(val *GetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response {
	return &NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response{value: val, isSet: true}
}

func (v NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRedfishV1SFSSInstanceZoneDBsConfigZoneAliasConfigDhanaSampleAliasZoneAliasMembersSourceConfig200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


