/*
SmartFabric Storage Software Application REST APIs

REST APIs used for managing SFSS application are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfss

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRedfishV1SFSSAppLicensesExpandLicenses200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRedfishV1SFSSAppLicensesExpandLicenses200Response{}

// GetRedfishV1SFSSAppLicensesExpandLicenses200Response 
type GetRedfishV1SFSSAppLicensesExpandLicenses200Response struct {
	// A set of licenses
	Licenses []GetRedfishV1SFSSAppLicensesExpandLicenses200ResponseLicensesInner `json:"Licenses"`
	// Number of licenses installed
	LicensesodataCount float32 `json:"Licenses@odata.count"`
	OdataId string `json:"@odata.id"`
	OdataContext string `json:"@odata.context"`
	OdataType string `json:"@odata.type"`
}

type _GetRedfishV1SFSSAppLicensesExpandLicenses200Response GetRedfishV1SFSSAppLicensesExpandLicenses200Response

// NewGetRedfishV1SFSSAppLicensesExpandLicenses200Response instantiates a new GetRedfishV1SFSSAppLicensesExpandLicenses200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRedfishV1SFSSAppLicensesExpandLicenses200Response(licenses []GetRedfishV1SFSSAppLicensesExpandLicenses200ResponseLicensesInner, licensesodataCount float32, odataId string, odataContext string, odataType string) *GetRedfishV1SFSSAppLicensesExpandLicenses200Response {
	this := GetRedfishV1SFSSAppLicensesExpandLicenses200Response{}
	this.Licenses = licenses
	this.LicensesodataCount = licensesodataCount
	this.OdataId = odataId
	this.OdataContext = odataContext
	this.OdataType = odataType
	return &this
}

// NewGetRedfishV1SFSSAppLicensesExpandLicenses200ResponseWithDefaults instantiates a new GetRedfishV1SFSSAppLicensesExpandLicenses200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRedfishV1SFSSAppLicensesExpandLicenses200ResponseWithDefaults() *GetRedfishV1SFSSAppLicensesExpandLicenses200Response {
	this := GetRedfishV1SFSSAppLicensesExpandLicenses200Response{}
	return &this
}

// GetLicenses returns the Licenses field value
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) GetLicenses() []GetRedfishV1SFSSAppLicensesExpandLicenses200ResponseLicensesInner {
	if o == nil {
		var ret []GetRedfishV1SFSSAppLicensesExpandLicenses200ResponseLicensesInner
		return ret
	}

	return o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) GetLicensesOk() ([]GetRedfishV1SFSSAppLicensesExpandLicenses200ResponseLicensesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Licenses, true
}

// SetLicenses sets field value
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) SetLicenses(v []GetRedfishV1SFSSAppLicensesExpandLicenses200ResponseLicensesInner) {
	o.Licenses = v
}

// GetLicensesodataCount returns the LicensesodataCount field value
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) GetLicensesodataCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.LicensesodataCount
}

// GetLicensesodataCountOk returns a tuple with the LicensesodataCount field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) GetLicensesodataCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LicensesodataCount, true
}

// SetLicensesodataCount sets field value
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) SetLicensesodataCount(v float32) {
	o.LicensesodataCount = v
}

// GetOdataId returns the OdataId field value
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) GetOdataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) GetOdataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataId, true
}

// SetOdataId sets field value
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) SetOdataId(v string) {
	o.OdataId = v
}

// GetOdataContext returns the OdataContext field value
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) GetOdataContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataContext
}

// GetOdataContextOk returns a tuple with the OdataContext field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) GetOdataContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataContext, true
}

// SetOdataContext sets field value
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) SetOdataContext(v string) {
	o.OdataContext = v
}

// GetOdataType returns the OdataType field value
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) GetOdataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataType
}

// GetOdataTypeOk returns a tuple with the OdataType field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) GetOdataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataType, true
}

// SetOdataType sets field value
func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) SetOdataType(v string) {
	o.OdataType = v
}

func (o GetRedfishV1SFSSAppLicensesExpandLicenses200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRedfishV1SFSSAppLicensesExpandLicenses200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Licenses"] = o.Licenses
	toSerialize["Licenses@odata.count"] = o.LicensesodataCount
	toSerialize["@odata.id"] = o.OdataId
	toSerialize["@odata.context"] = o.OdataContext
	toSerialize["@odata.type"] = o.OdataType
	return toSerialize, nil
}

func (o *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Licenses",
		"Licenses@odata.count",
		"@odata.id",
		"@odata.context",
		"@odata.type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRedfishV1SFSSAppLicensesExpandLicenses200Response := _GetRedfishV1SFSSAppLicensesExpandLicenses200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRedfishV1SFSSAppLicensesExpandLicenses200Response)

	if err != nil {
		return err
	}

	*o = GetRedfishV1SFSSAppLicensesExpandLicenses200Response(varGetRedfishV1SFSSAppLicensesExpandLicenses200Response)

	return err
}

type NullableGetRedfishV1SFSSAppLicensesExpandLicenses200Response struct {
	value *GetRedfishV1SFSSAppLicensesExpandLicenses200Response
	isSet bool
}

func (v NullableGetRedfishV1SFSSAppLicensesExpandLicenses200Response) Get() *GetRedfishV1SFSSAppLicensesExpandLicenses200Response {
	return v.value
}

func (v *NullableGetRedfishV1SFSSAppLicensesExpandLicenses200Response) Set(val *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRedfishV1SFSSAppLicensesExpandLicenses200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRedfishV1SFSSAppLicensesExpandLicenses200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRedfishV1SFSSAppLicensesExpandLicenses200Response(val *GetRedfishV1SFSSAppLicensesExpandLicenses200Response) *NullableGetRedfishV1SFSSAppLicensesExpandLicenses200Response {
	return &NullableGetRedfishV1SFSSAppLicensesExpandLicenses200Response{value: val, isSet: true}
}

func (v NullableGetRedfishV1SFSSAppLicensesExpandLicenses200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRedfishV1SFSSAppLicensesExpandLicenses200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


