/*
SmartFabric Storage Software Application REST APIs

REST APIs used for managing SFSS application are captured in this section.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sfss

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRedfishV1SFSSAppAuthenticationSequence200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRedfishV1SFSSAppAuthenticationSequence200Response{}

// GetRedfishV1SFSSAppAuthenticationSequence200Response 
type GetRedfishV1SFSSAppAuthenticationSequence200Response struct {
	// Defines a set of authentication servers (local and remote) configured in SFSS and the order in which SFSS looks up user information in these servers
	AuthenticationSequence []string `json:"AuthenticationSequence"`
	OdataId string `json:"@odata.id"`
	OdataType string `json:"@odata.type"`
	OdataContext string `json:"@odata.context"`
}

type _GetRedfishV1SFSSAppAuthenticationSequence200Response GetRedfishV1SFSSAppAuthenticationSequence200Response

// NewGetRedfishV1SFSSAppAuthenticationSequence200Response instantiates a new GetRedfishV1SFSSAppAuthenticationSequence200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRedfishV1SFSSAppAuthenticationSequence200Response(authenticationSequence []string, odataId string, odataType string, odataContext string) *GetRedfishV1SFSSAppAuthenticationSequence200Response {
	this := GetRedfishV1SFSSAppAuthenticationSequence200Response{}
	this.AuthenticationSequence = authenticationSequence
	this.OdataId = odataId
	this.OdataType = odataType
	this.OdataContext = odataContext
	return &this
}

// NewGetRedfishV1SFSSAppAuthenticationSequence200ResponseWithDefaults instantiates a new GetRedfishV1SFSSAppAuthenticationSequence200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRedfishV1SFSSAppAuthenticationSequence200ResponseWithDefaults() *GetRedfishV1SFSSAppAuthenticationSequence200Response {
	this := GetRedfishV1SFSSAppAuthenticationSequence200Response{}
	return &this
}

// GetAuthenticationSequence returns the AuthenticationSequence field value
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) GetAuthenticationSequence() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AuthenticationSequence
}

// GetAuthenticationSequenceOk returns a tuple with the AuthenticationSequence field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) GetAuthenticationSequenceOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthenticationSequence, true
}

// SetAuthenticationSequence sets field value
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) SetAuthenticationSequence(v []string) {
	o.AuthenticationSequence = v
}

// GetOdataId returns the OdataId field value
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) GetOdataId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataId
}

// GetOdataIdOk returns a tuple with the OdataId field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) GetOdataIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataId, true
}

// SetOdataId sets field value
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) SetOdataId(v string) {
	o.OdataId = v
}

// GetOdataType returns the OdataType field value
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) GetOdataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataType
}

// GetOdataTypeOk returns a tuple with the OdataType field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) GetOdataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataType, true
}

// SetOdataType sets field value
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) SetOdataType(v string) {
	o.OdataType = v
}

// GetOdataContext returns the OdataContext field value
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) GetOdataContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OdataContext
}

// GetOdataContextOk returns a tuple with the OdataContext field value
// and a boolean to check if the value has been set.
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) GetOdataContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OdataContext, true
}

// SetOdataContext sets field value
func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) SetOdataContext(v string) {
	o.OdataContext = v
}

func (o GetRedfishV1SFSSAppAuthenticationSequence200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRedfishV1SFSSAppAuthenticationSequence200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["AuthenticationSequence"] = o.AuthenticationSequence
	toSerialize["@odata.id"] = o.OdataId
	toSerialize["@odata.type"] = o.OdataType
	toSerialize["@odata.context"] = o.OdataContext
	return toSerialize, nil
}

func (o *GetRedfishV1SFSSAppAuthenticationSequence200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"AuthenticationSequence",
		"@odata.id",
		"@odata.type",
		"@odata.context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRedfishV1SFSSAppAuthenticationSequence200Response := _GetRedfishV1SFSSAppAuthenticationSequence200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRedfishV1SFSSAppAuthenticationSequence200Response)

	if err != nil {
		return err
	}

	*o = GetRedfishV1SFSSAppAuthenticationSequence200Response(varGetRedfishV1SFSSAppAuthenticationSequence200Response)

	return err
}

type NullableGetRedfishV1SFSSAppAuthenticationSequence200Response struct {
	value *GetRedfishV1SFSSAppAuthenticationSequence200Response
	isSet bool
}

func (v NullableGetRedfishV1SFSSAppAuthenticationSequence200Response) Get() *GetRedfishV1SFSSAppAuthenticationSequence200Response {
	return v.value
}

func (v *NullableGetRedfishV1SFSSAppAuthenticationSequence200Response) Set(val *GetRedfishV1SFSSAppAuthenticationSequence200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRedfishV1SFSSAppAuthenticationSequence200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRedfishV1SFSSAppAuthenticationSequence200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRedfishV1SFSSAppAuthenticationSequence200Response(val *GetRedfishV1SFSSAppAuthenticationSequence200Response) *NullableGetRedfishV1SFSSAppAuthenticationSequence200Response {
	return &NullableGetRedfishV1SFSSAppAuthenticationSequence200Response{value: val, isSet: true}
}

func (v NullableGetRedfishV1SFSSAppAuthenticationSequence200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRedfishV1SFSSAppAuthenticationSequence200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


